### ISSUE TITLE
Incomplete NFL data?

### ISSUE THREAD

**Issue by kinelarty** [roclark/sportsreference#131]
I've successfully run through your examples for getting NFL Player data (i.e. Brees), but when I look to get data on other players (specifically, receivers like Julio Jones or Wes Welker), there seems to be very little actual specific data (i.e. receiving_yards, etc.).  Simple example: 

from sportsreference.nfl.roster import Player
jones = Player('JoneJu02')
stats = jones.dataframe[["games", "receptions"]]
>>> stats
        games receptions
2011       13       None
2012       16       None
2013        5       None
2014       15       None
2015       16       None
2018       16       None
Career    111       None

Totally open to the idea I'm just missing something basic, so apologies in advance if that's the case.  Thanks.

**Comment by roclark** [comment]
Hey @kinelarty, thanks for reaching out, and my apologies for the lengthy time to respond! I was able to track this down this morning. It appears that sports-reference.com changed the name of the table I was pulling the player's rushing and receiving information from `rushing_and_receiving` to `receiving_and_rushing`. Since I was looking for the wrong table name, it made it appear it didn't exist, causing those statistics to be empty as you saw. Luckily, it's an easy fix where I now search for both of the table names I listed above. I will create a PR shortly and get this merged in master.

BTW, this is what I'm seeing now:
```python
from sportsreference.nfl.roster import Player

jones = Player('JoneJu02')
stats = jones.dataframe[["games", "receptions"]]
print(stats)
```
```
        games  receptions
2011       13          54
2012       16          79
2013        5          41
2014       15         104
2015       16         136
2016       14          83
2017       16          88
2018       16         113
Career    111         698
```

Something's obviously wrong if it's saying both Julio Jones and Wes Welker had zero receptions. :smiley:

I will get this resolved shortly! Thanks again!
