### ISSUE TITLE
sportsreference.ncaaf.roster does not include a passing_yards attribute

### ISSUE THREAD

**Issue by soySmelliot** [roclark/sportsreference#158]
**Describe the bug**
When using the Roster() function from sportsreference.ncaaf.roster, there is no passing_yards attribute in the player dataframes. 

**To Reproduce**
>>> nebraska = Roster('Nebraska', year = 2018)
>>> for player in nebraska.players:
...     print(player.dataframe.passing_yards)
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Users\Elliot\Anaconda3\envs\main\lib\site-packages\pandas\core\generic.py", line 5067, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'passing_yards'

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Sportsreference Version 0.4.3

**Comment by roclark** [comment]
Hello again @soySmelliot, you are absolutely right! Looks like the `passing_yards` attribute was just in the `BoxscorePlayer` class but not a part of the `AbstractPlayer` class. Since both the `BoxscorePlayer` (part of the `boxscore` module) and `Player` (part of the `roster` module) classes inherit `AbstractPlayer`, any properties under the `AbstractPlayer` will be included in the two former classes. With `passing_yards` only under `BoxscorePlayer`, it was not showing up with `Player` objects when querying rosters, hence the missing attribute. I made a change already and am undergoing some final tests, but I will create a PR with the fix shortly. In the meantime, I can now run the following:

```python
from sportsreference.ncaaf.roster import Roster

nebraska = Roster('Nebraska', year=2018)

for player in nebraska.players:
    print(player.name, player.passing_yards)
```
which outputs...
```
Adrian Martinez 2617
Andrew Bunch 320
Noah Vedral 305
Matt Masker None
Maurice Washington 0
Devine Ozigbo None
...
```

Thanks again for reporting this and for your help in other issues, I greatly appreciate it! Also, as a fellow Big Ten fan, I wish your team all the best this coming season!
