### ISSUE TITLE
Add a usage example for sportsreference.nfl.teams.Team(team_data, rank, year=None)

### ISSUE THREAD

**Issue by ticklingthedata** [roclark/sportsreference#159]
I tried to create a team object as following:
```
from sportsreference.nfl.teams import Team
team = Team('https://www.pro-football-reference.com/teams/sfo/1970.htm', 1, 1970)
```
I assume I'm guessing wrong by considering `team_data` as the link to the team data for this specific season. I also tried with one of the team data like `abbreviation`, but still having an exception about `abbr` which seem out of the expected regex.

Could you please pinpoint what I'm doing wrong or/and add a usage example of `sportsreference.nfl.teams.Team` to the doc? 

Great work btw!

Thank you.

**Comment by roclark** [comment]
Hey @ticklingthedata, thanks for the issue and for the kind words!

To answer your question, as originally designed, I actually didn't intend for end-users to call the `Team` class directly. Instead, I planned for users to instantiate the `Teams` (with an 's' at the end) class and call any specific teams using the returned object instead. For example, if you wanted to grab data from the 49ers' 1970 season, you would run the following code:

```python
from sportsreference.nfl.teams import Teams

team = Teams(year=1970)
sfo = team('SFO')
```

The `sfo` object will point be an instance of the `Team` class specifically targeting San Francisco's season in 1970. This way, you don't have to worry about manually pulling webpages or tracking down URLs.

Now, I agree that this isn't exactly intuitive as you would expect to call the `Team` class if you only care about a single team. However, after an attempt to re-design the `Team` class and allow it to be instantiated directly, I found that, due to the structure of data on the www.sports-reference.com pages, the code would perform equivalent work between pulling all NFL teams as it would pulling a single NFL team since the page I pull data from contains all teams together and is parsed in one shot for all teams.

With that being said, I still want to find a better way to call a single team directly, especially if you have no desires in pulling data from any other teams. On a simple level, I could create a wrapper for `Team` that calls `Teams` underneath but only returns a single team. While that would work, I just worry it would create too much bloat. I am open to any suggestions you might have though!

Thanks again for taking the time to write this and for the feedback! I greatly appreciate it and apologize for the delay in getting back!

**Comment by roclark** [comment]
With the work associated with #360, it is now possible to call the `Team` class directly. While most of the modules still end up pulling stats for all teams in a league (given that most stats pages include all team stats anyway - it's computationally cheap to pull all stats), the modules avoid instantiation of all teams except the desired one which reduces execution time by an order of magnitude or more. Going back to your example, you can now run the following:

```python
from sportsreference.nfl.teams import Team

sfo = Team(team_name='SFO', year=1970)
```

I am going to close this now given the updates as this should hopefully make this much easier to get up and running. Also, the documentation has been updated with the inclusion of #360 and all associated PRs.
