### ISSUE TITLE
NCAAF Teams for current season (2019) is empty

### ISSUE THREAD

**Issue by naymikm** [roclark/sportsreference#179]
**Describe the bug**
Teams seems to not be updated to current year

**To Reproduce**
Sample code which causes an issue.
```
from sportsreference.ncaaf.teams import Teams
#teams = Teams(2019) same issue
teams = Teams()
...
    "Document is empty")
lxml.etree.ParserError: Document is empty

```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - sportsreference==0.4.3

**Comment by roclark** [comment]
Hey @naymikm, thanks for reporting this! Looks like this is an issue with the ACC not containing any inference on their conference page yet. For reference, at the time of writing, the [ACC page](https://www.sports-reference.com/cfb/conferences/acc/2019.html) is currently an empty document, which is the cause of the error you are running into. Adding a handler for this is trivial, but this starts to get tricky as the `Teams` class relies on information from the `Conferences` class (which is where the error is actually being thrown). Without a valid response from the `Conferences` class, the `Teams` class can't continue with the way it is currently implemented. I think I have some ideas on how to resolve this issue, such as reverting to conference information from the previous year if the current page is invalid, but that isn't necessarily the prettiest solution as conferences realign periodically. Perhaps there is a way to safely omit any information that can't be retrieved yet. I would rather have missing data than incorrect data since the former can be worked around, whereas it's hard to determine if data is incorrect without much deeper analysis.

I will get working on this and create a patch when I get it figured out. Thanks again for creating the issue! Assuming no other issues are created by the time I get this resolved, this will be the final update I make before releasing 0.4.4.
