### ISSUE TITLE
NBA Home and Away points returning the same value

### ISSUE THREAD

**Issue by joaonobre** [roclark/sportsreference#207]
**Describe the bug**
I noticed that the Home points is equal to Away points, at least in 10 games I tested.

**To Reproduce**
from sportsreference.nba.boxscore import Boxscore

game_data = Boxscore('201806080CLE')
print(game_data.away_points)  # Prints 108
print(game_data.home_points)  # Prints 85

**Expected behavior**
The number of points is correct.

**Screenshots**
Check this example, it prints 108 for both values.
![image](https://user-images.githubusercontent.com/26253489/65895777-e7d23c00-e3a3-11e9-98cb-d70cd81df46c.png)

What can be causing this problem? Can it be specific to me or is it a problem on the the library code?
Thanks in advance!

**Comment by roclark** [comment]
Thanks for sending this @joaonobre! I just duplicated this on my side, so this is definitely not just something on your end (which is always a good feeling, isn't it? 😃). I haven't gotten down to the root cause of this yet, but I imagine it is something to do with the parsing scheme used to pull the scores on the Boxscore page. I will investigate further and create a patch for this so we can get back to the expected behavior.

Thanks again for letting me know of this!

**Comment by roclark** [comment]
As an update, it looks like the team at sports-reference.com either added more places where the score is displayed on the page, and/or changed the IDs for the existing points totals, throwing off the indexing I was using while grabbing the home and away scores. Luckily, this is an easy fix as I can just query the first and last score that is retrieved as those will be the away and home, respectively. As mentioned, I will create a small patch for this, but am in the process of migrating from Travis-CI to GitHub Actions for my testing suite, and will probably want to merge that prior to any new updates since the project is in an interesting transition period between the two at the moment (shouldn't be long).

**Comment by joaonobre** [comment]
No problem! I also expected a change in the structure of the page to be causing this problem. Glad it's easy to solve!
Thanks for the quick response, great work with this API! :)

**Comment by roclark** [comment]
Thanks again for the kind words! 😃 I just created PR #210 which should resolve this issue. I now can do the following:

```python
from sportsreference.nba.boxscore import Boxscore

game_data = Boxscore('201806080CLE')
print(game_data.away_points)
print(game_data.home_points)

#108 
#85
```
