### ISSUE TITLE
#254 Still not resolved

### ISSUE THREAD

**Issue by oneshotbob** [roclark/sportsreference#274]
**Describe the bug**
The bug from #254 is not resolved. I have upgraded to version 0.4.6 and I'm still getting the following error when using teams=Teams() in the NFL package

HTTPError: HTTP Error 404: Not Found

**To Reproduce**
Sample code which causes an issue.
```
from sportsreference.nfl.teams import Teams

teams = Teams()
for team in teams:
    print(team.name)  # Prints the team's name
    # Prints the team's average margin of victory
    print(team.margin_of_victory)
```

**Expected behavior**
This should give me the team's margin of victory
**Screenshots**
Instead it gives the following error
![image](https://user-images.githubusercontent.com/53715473/69215840-8ca90400-0b1f-11ea-99dc-e9a9d538111e.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Sportsreference Version [0.4.6]

**Additional context**
Add any other context about the problem here. If applicable, also include links to any pages on www.sports-reference.com that are believed to be causing this issue.

**Comment by roclark** [comment]
Hey @oneshotbob! As mentioned in #254, the latest wheel released on PyPI (version 0.4.6) does _not_ have the fix yet, but the upstream master should be working now as the patch has been merged with that branch. Once I cut another release (which will be very soon at this point), you should be able to use the latest wheel, but in the meantime, source should work (I just ran the code below using the latest master code):

```python
from sportsreference.nfl.teams import Teams

teams = Teams()
for team in teams:
    print(team.name)
    print(team.margin_of_victory)

Baltimore Ravens
14.5
Kansas City Chiefs
4.7
San Francisco 49ers
14.0
...
```

If you try the upstream code, however, and find that it too doesn't work, please let me know. Otherwise, I will close this as the fix should already be working.
