### ISSUE TITLE
Looping through Roster object 2019

### ISSUE THREAD

**Issue by jcurrey** [roclark/sportsreference#29]
**Describe the bug**
I'm getting a xml parsing error when I loop through the Rosters for 2019, but not any other year.

**To Reproduce**
Sample code which causes an issue.
```python
from sportsreference.ncaab.roster import Roster

bama = Roster('ALABAMA')
for player in bama.players:
    # Prints the name of all players who played for Alabama in the most
    # recent season.
    print(player.name)
    
print("At least we've got football")
```

**Expected behavior**
Print the players name.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Sportsreference Version 0.3.1

**Additional context**
I'm really wondering if this is just on my setup or if Sports Reference is doing something different on their site.  Here's the link:  https://www.sports-reference.com/cbb/schools/alabama/2019.html 

This happens to me on the sample code too, the Bama fan in me change just changed the team :)
This really is an incredible project!

**Comment by roclark** [comment]
Thanks for bringing this to my attention @jcurrey! Sorry you ran into this, but I'm grateful you are a Bama fan and tried this out, because it identified a bug in the code that won't showup for most other schools. :smile: While troubleshooting this, I found that the code was able to parse _some_ players on Alabama's roster, but not all. The specific culprit appears to be Javian Davis-Fleming. If you look at his [player page](https://www.sports-reference.com/cbb/players/javian-davis-fleming-1.html), it contains no stats, and the code threw an error while trying to parse certain stats tables from the page when they don't exist. I will add some more error checkers to the `Roster` and `Player` classes to prevent this error from being thrown, and attempt to pull as much information from each player as I can, regardless of how little that may be.

Since this is a bug that limits functionality of the code, I will work on a patch release to fix this immediately. Thanks again!

BTW, best of luck to the Crimson Tide this weekend!

**Comment by jcurrey** [comment]
Thanks!  

This really is an incredible project, so big thanks @roclark!  I'll sign off with a little Roll Tide!

**Comment by roclark** [comment]
@jcurrey, I believe this should now be resolved. In PR #48 which I just closed, I was able to successfully query the current roster for Alabama and print all of the names. I will work on another minor patch and then create a version 0.3.2 of the package which will include this fix. Otherwise, the latest code in master should suffice.

Please let me know if you have further troubles!
