### ISSUE TITLE
NFL Roster Error(s)

### ISSUE THREAD

**Issue by denutza** [roclark/sportsreference#376]
While processing many of the Rosters, many come back with the error: 
ParserError: Document is empty

**This happens over a wide range of years and teams.**

from sportsreference.nfl.roster import Roster
 r=Roster('CIN',1990)

**Comment by roclark** [comment]
Hello @denutza, thanks for the issue! I actually just ran into this myself and created a small patch to resolve this issue. It looks like this is due to some player pages being invalid/missing/incomplete, especially for some of the earlier seasons, which causes the `ParserError` as there is no information to pull. I will create a PR and get the patch merged shortly so it can be resolved for my next release which should come relatively soon.

Thanks again!
