### ISSUE TITLE
Sportsreference.fb not working

### ISSUE THREAD

**Issue by Maths-Lad** [roclark/sportsreference#385]
I successfully installed the sportsreference package and all the sports codes work well, apart from football. 

When I use for example the code:
' from sportsreference.fb.team import Team

tottenham = Team('Tottenham Hotspur')
print(tottenham.goals_scored) '

It gives me an error: [No module named sportsreference.fb]

I also switched "team" with "teams" but that also did not work.

How can I fix this?

**Comment by roclark** [comment]
Hey @Maths-Lad, thanks for the report! Quick check - which version of the `sportsreference` package are you using? Is it 0.5.0 or later?

**Comment by Maths-Lad** [comment]
Hi roclark, thank you for your response. I think I am using the 0.5.1 package. 
(I followed the steps on https://github.com/roclark/sportsreference if that helps in any way.)

**Comment by roclark** [comment]
Just took a deeper dive into this, and it appears that a file was missing which breaks production deployments (ie. the official binary which you downloaded), but doesn't have an affect on development environments, which is why it didn't show up in the testing suite. I will make a fix for this ASAP and generate a new release so this is sorted out from here.

Thank you very much for bringing this to my attention!

**Comment by Maths-Lad** [comment]
You are very welcome.
