### ISSUE TITLE
Using .weight when creating dataframe.

### ISSUE THREAD

**Issue by calebrichards** [roclark/sportsreference#403]
I was creating a dataframe with a large number of players and ran into an AttributeError with one of the players in the NFL using Player class from roster module. 

`AttributeError: 'NoneType' object has no attribute 'replace'`

The issue was that there was no weight recorded for the player even though he had other statistics and using the .weight method calls .replace which cannot be called on type None.

You can reproduce with 
`Player('DorsKe01').weight`

I'm not entirely sure what we should expect from this either. Should this give 0 or nan? For right now, I added a conditional return to the .weight method that looks like the following and it is working for my purposes.

My Fix
```
    @property
    def weight(self):
        """
        Returns an ``int`` of the player's weight in pounds.
        """
        if self._weight is None:  #new lines here
            return self._weight    #new lines here
        return int(self._weight.replace('lb', ''))
```

 - OS: Windows 10
 - Sportsreference Version 0.5.2

**Comment by roclark** [comment]
Hello @calebrichards, thanks for reporting this! Yes, this is an issue that was raised in #393 and has been patched with #399. With the latest master branch, the following now works:

```python
from sportsreference.nfl.roster import Player

weight = Player('DorsKe01').weight
```

Since he doesn't have a weight listed on his page, `weight` will be `None`.

Once I drop the next release, scheduled for version 0.6.0, this will be included with the new binaries. In the meantime, feel free to use the latest source code.

Thanks again!
