### ISSUE TITLE
Can't get NBA schedules

### ISSUE THREAD

**Issue by scaratozzolo** [roclark/sportsreference#462]
Trying to pull schedules for various teams results in a 404 error. This was working a few days ago so not sure what happened.

```python
from sportsreference.nba.schedule import Schedule

Schedule("MIL") # urllib.error.HTTPError: HTTP Error 404: Not Found
```

Desktop (please complete the following information):
 - OS: Windows 10
 - Sportsreference Version: 0.5.2
 - Python 3.8.5 and 3.7.2

**Comment by jiwoongim** [comment]
I get same problem as well:
``` 
year =2018
 doc = pq(SEASON_PAGE_URL % year)

urllib.error.HTTPError: HTTP Error 404: Not Found
```
It used to work before... 
Any ideas?

**Comment by jiwoongim** [comment]
Looks like it works now

**Comment by scaratozzolo** [comment]
Not for me, I'm still getting an error.

**Comment by scaratozzolo** [comment]
It seems that by specifying the year the issue is resolved, which I didn't have to do before but it's fine.

```python
sched = Schedule("MIL") # 404
sched = Schedule("MIL", year="2020") # solution
```

**Comment by roclark** [comment]
Hey all, sorry for not getting to this earlier, but as mentioned in #464, this turned out to be a logical issue with how `sportsreference` finds the default year given the start of the next NBA season has been severely delayed due to the pandemic. This has since been resolved, so you should be able to pull the NBA modules without specifying the year at this point. But, great work in finding a workaround! 😃
