### ISSUE TITLE
Schedule for upcoming games

### ISSUE THREAD

**Issue by tylerjlawson** [roclark/sportsreference#56]
I noticed that in your documentation you say Schedule() returns all scheduled games for any given team in any league. I am finding that This function returns all played games from a given year. I am sorry if this is already possible or if I am simply doing something wrong, but I would like to be able to pull in upcoming games on a given schedule as well.

**Comment by roclark** [comment]
Hey @tylerjlawson! Thanks for the question! To help me better understand, are you wondering if it is possible to get the schedule of a team for seasons outside of the current or most recent (as in, get a team's schedule during the year 2000)? If so, the `Schedule` class has an optional second parameter which can be used to specify a particular year. The following code grabs Michigan State's basketball schedule from the 2011 season:

```python
from sportsreference.ncaab.schedule import Schedule

# Grab MSU's schedule from the 2010-11 season
msu_schedule = Schedule('MICHIGAN-STATE', year='2011')
for game in msu_schedule:
    print(game.date)  # Prints the date the game was played
    print(game.result)  # Prints whether the team won or lost
    # Creates an instance of the Boxscore class for the game.
    boxscore = game.boxscore
```

Is this what you are looking for? Or is there further functionality that you desire?

**Comment by tylerjlawson** [comment]
Hi Robert, I am aware you can do other seasons. I was looking to get games from the current season before a game has occurred. Right now when I run the schedule function on this current season I get all of the games that have been played already, but I do not get results for games happening tomorrow or the day after.

**Comment by roclark** [comment]
Thanks for the clarification @tylerjlawson, good to know! By default, the tool is supposed to grab the entire schedule for each team for the current season regardless of whether or not the game has been played. If you aren't able to capture this information, this sounds like a bug that I need to look into. If you wouldn't mind sending me some code, I can get started on figuring this out and publish a fix.

Thanks again for sharing this!

**Comment by tylerjlawson** [comment]
No problem, happy to help. 

from sportsreference.nba.schedule import Schedule
import datetime

def get_boston_three():
	sched = Schedule('BOS')
	# sched[-3:] should be last three games of season
	# today is 2019-03-15
	# these are the past three games played rather than last of season
	# prints 2019-03-09, 2019-03-11, 2019-03-14
	for game in sched[-3:]: 
		print(game.date)

	# celtics play wizards on 2019-04-09
	celtics_last_game = "2019-04-09"
	all_dates = [game.date for game in sched]
	assert celtics_last_game in all_dates

**Comment by roclark** [comment]
Ah yes, that's definitely an issue, thank you for bringing it to my attention! I will work on the creating a patch for this and releasing it as soon as I can. I would have expected the game played on April 9th to be included with the schedule, so something's not quite right. I will update here when I make progress. Thanks again!

**Comment by roclark** [comment]
I found out where this issue originates from. The code pulls the team's gamelog (ex. for the [Celtics](https://www.basketball-reference.com/teams/BOS/2019/gamelog/)) which only includes information up to the most recently completed game for the team. I originally chose the game log since it contained more information for each game which could be included without going down to the `boxscore` level. Unfortunately, since I wrote the code during the offseason, I didn't realize they only show part of the schedule instead of the entire slate of games.

I agree with you, I think it is preferred to have the entire schedule instead of just the completed games (and this is the functionality of most other sports in the API), so I will change the affected sports to use the schedule page (ex. schedule for the [Celtics](https://www.basketball-reference.com/teams/BOS/2019_games.html)). This will lower the amount of information that is presented in the `Game` class in the `schedule` module, but that information is still accessible by going down to the `boxscore` level if desired, so I think that's an OK tradeoff.

I will work on updating this code and creating a patch. Thanks again for bringing it to my attention!

**Comment by tylerjlawson** [comment]
If you need or want assistance on fixing this bug or others, I am very interested in the project and would be happy to try to help.

**Comment by roclark** [comment]
Thanks @tylerjlawson! I’ve got a fix coming soon (just need to update the tests and I will be finished), so I think I can take care of this one, but if there’s anything else that is giving you issues or if there are new features you would like to see added, I welcome any Pull Requests with additional code! This project has grown a lot as a result of the requests from the community, and I feel having others contribute to the codebase would make it even stronger.

Thanks again for your support!

**Comment by roclark** [comment]
I just opened up PR #60 which uses the team schedule instead of the gamelogs, so now all games are accessible from `Schedule` class, even if they haven't occurred yet. Once the testing suite finishes, I will merge the PR and cut a new release of the project to get the update in the wild.

One caveat, while your code above will now return the last three games of the season, the way the date is displayed on the new schedule page is different, and is now in the format "Tue, April 9, 2019" instead of "4-9-2019". As a result, your code will throw an error during the assertion as it tries to compare "Tue, April 9, 2019" with "4-9-2019". So, nothing is wrong with how you are using the code, but just wanted to give a warning that the actual date output looks different now.

Let me know if you have any concerns with this, otherwise I will get you a new release!

**Comment by tylerjlawson** [comment]
Thank you! The date format makes no difference to me.

**Comment by roclark** [comment]
Just FYI, I cut version 0.4.1 a few moments ago which includes this update. The new package should be released to PyPI and available for upgrading via PIP within the hour. Thanks again for identifying this!
