### ISSUE TITLE
MLB Teams HTTP Error

### ISSUE THREAD

**Issue by Goggins105** [roclark/sportsreference#61]
I am just trying to basic data on all mlb teams, but I get an urllib.HTTPError

from sportsreference.mlb.teams import Teams

teams = Teams()
for team in teams:
    print(team.name)

**Expected behavior**
Instead of printing each team's name I get

 urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by roclark** [comment]
Hey @Goggins105! Thanks for bringing this to my attention. Looks like this is caused by the utilities selecting the 2019 MLB season while running the code right now. Since the season hasn't started yet, the team at sports-reference.com hasn't added any team information to the website, so `sportsreference` fails to find the required information. While I can't do anything about the information not being present, I can add better information on why the 404 error is being thrown, or possibly throw a warning and go back to last year until the new season has started. Regardless, this is something that I need to fix (and it will effect all sports as well). I will work on an update and generate version 0.4.2 with the fix.

Thanks again!

**Comment by roclark** [comment]
@Goggins105 at this point, the issue resolved itself now that the 2019 MLB season has started, though this still exposes an issue that I need to fix for the future whenever a new season is about to begin for a sport, but the expected page isn't loaded yet on www.sports-reference.com.
