### ISSUE TITLE
Schedule Module Error

### ISSUE THREAD

**Issue by zakraicik** [roclark/sportsreference#72]
**Description**
Cannot instantiate schedule object.  Receive "TypeError: 'NoneType' object is not iterable"

**To Reproduce**
```
from sportsreference.nba.schedule import Schedule
boston_schedule = Schedule('BOS')
```

**Expected behavior**
Expect to be able to use object to iterate over desired team's schedule. 

**Screenshot**
<img width="838" alt="Screen Shot 2019-04-08 at 7 02 19 PM" src="https://user-images.githubusercontent.com/43297285/55762422-ee08e080-5a30-11e9-933c-d329645c4808.png">

**Comment by roclark** [comment]
Thanks for the issue @zakraicik! I apologize for the delayed response! I will look into this issue. I wonder if this is in part due to the regular season coming to an end for the Celtics, so no games are being populated in the playoffs table, even though they made the playoff. I will get a fix for this once I investigate further. Thanks again!

**Comment by roclark** [comment]
@zakraicik turns out this was an issue where I made a comparison with a particular string in the HTML page that should only occur when playoff games are included in the team's schedule page, but at present (before the games are listed on the team's page but they made the playoffs), the string I was comparing against occurred despite the table being present. This threw the error you are seeing since it can't pull the table.

I now directly check for the table ID for playoff games which is working in the tests.

Thanks again for bringing this to my attention!

**Comment by zakraicik** [comment]
No problem!
