### ISSUE TITLE
SR Data Use Policy

### ISSUE THREAD

**Issue by zakraicik** [roclark/sportsreference#76]
Does this project comply with SR's data use policy? 

https://www.sports-reference.com/data_use.html

**Comment by roclark** [comment]
Hello again @zakraicik! This is a great and very important question. Two items stand out to me in their data use policy:

> As an aside, copyright law is clear that facts cannot be copyrighted, so you are free to reuse facts found on this site in accordance with copyright laws.

I interpret this statement as all statistical and factual categorical data found on their website is in the public domain and free for our collection. Therefore, I believe we have the legal right to the information.

> However, I would point out that learning how to accumulate data is often a more valuable skill than actually analyzing the data, so we encourage you as a student or professional to learn how.

I see this statement as them being open to and encouraging the collection of data for analysis for multiple applications.

I don't see any statements that explicitly (or implicitly) prohibit this project from collecting data in the way that it does. Further, usage of the package also passes the [robots.txt](https://www.sports-reference.com/robots.txt) file.

Now, this is all my personal interpretation of their data use policy after multiple reads over the past several months. But, others may see it differently, and I would love any further input on this topic.

Thanks again for posting this crucial question!

**Comment by zakraicik** [comment]
Great points. The piece of the data use policy that concerns me is 

> There are a couple of additional mitigating factors. For some of our datasets, our licenses completely preclude any redistribution of the data. And, in some cases, we cannot even give you explicit permission to reuse en masse what you find on the site. Additionally, we need to block any aggressive spidering of the site to maintain site performance for non-bot traffic (i.e. actual people using the site).

I have not spent too much time familiarizing myself with how the API works, but it was a thought that came to my mind.

**Comment by roclark** [comment]
I apologize for the radio silence on this thread! Thanks again for adding additional insight and pointing this out. This is another key statement that should be addressed as well. While I too have concerns about that statement, `sportsreference` doesn't make calls to the site that break the robots.txt script, so we should be safe from the last line of the policy you quoted above. Granted, anyone can take the package and abuse it by initiating thousands of calls in parallel with massive amounts of hardware if they desire, but I'd argue that this issue is beyond the realm of the package as this is more of a DDoS attack and not an exploit or violation caused by `sportsreference`.

As for the licenses precluding redistribution of data, that should only pertain to the non-factual information on the site, such as articles and assets (logos and pictures have special licenses). I believe we should still be ok in this regard.

Again, thanks for sharing this. Please let me know if you disagree with any of my points above. In my mind, we should be safe since we are only pulling factual data, but I could be incorrect in that assessment.
