### ISSUE TITLE
Support scraping data from local files

### ISSUE THREAD

**Issue by hodger** [roclark/sportsreference#9]
Hi @roclark! Really like the project. What do you think of supporting local HTML files that have been downloaded from sports-reference in advance?

Could be nice to let users specify that they've pre-downloaded certain resources through some kind of API configuration, maybe with a mapping like `{'some-resource-id': 'path_to_resource_page.html'}`

After looking through the code a bit, maybe this could happen in `utils.py` with some new function that gets a document, choosing between `PyQuery(url=x)` and `PyQuery(filename=x)`?

**Comment by roclark** [comment]
Hey @hodger, thanks for passing this along! I can see many valuable reasons to include the ability to read offline content and think this is a good feature to include in the future. I have to admit, I never considered this when I first thought up the project, but it makes a lot of sense now that you mention it.

I think it would be good to discuss the implementation part further to make sure I fully understand your ideas, and to ensure we do this the right way. I agree, I think adding something in `utils.py` that is able to determine where to read the HTML from would be wise. Using the current class structures, do you envision having a user add a parameter to specify the HTML location while instantiating a class? For example, to get the NCAAB teams using local HTML files, run something like the following?

```python
from sportsreference.ncaab.teams import Teams

for team in Teams(html="path/to/local/html"):
    print("I read %s's info from a local file!" % team.name)
```

Any more advice or thoughts would be much appreciated! Or, feel free to mock up an example or create a pull request and I'd be happy to check it out! Otherwise, I will keep this here and add it to my roadmap for inclusion in a future release.

Thanks again for using this repository and opening this issue, I greatly appreciate all of the feedback I can get!

**Comment by hodger** [comment]
I think a class parameter that specifies the name of a directory where HTML files live is probably a good idea. Then I imagine passing that directory to the utils function, where it could check if local files exist before grabbing them from the site. 

It may be good to let users generate the directory of historical HTML (or cleaner data if possible?) with a separate command, so they don't have to be familiar with what specific pages the API is using. So something like:

```python
from sportsreference import downloader

downloader.download(sport='ncaaf', year=2014, to="./local_html")
```

I'm happy to create a WIP pull request that we could discuss.

**Comment by roclark** [comment]
I like your idea of the downloader, I think that would clear up a lot here! Also, allowing the user the option to specify local HTML files and downloading them if necessary would be helpful in order to minimize confusion as to which pages are needed for each class.

You are more than welcome to create a PR for this if you desire. I am focused on adding a few other features at the moment (including creating a website for a related project), so I don't think I will be able to get to this immediately, but as mentioned, this is definitely something I see value in and would like to include. It just might take me a bit before I can call it complete. :smile:

**Comment by vesper8** [comment]
this sounds like an excellent idea.. it also limits the amount of hammering on their resources when people are developing and getting to learn how to use this. In general when I do web scraping I also first download the html locally once and then from that point forward I only hit the local file.. it just seems more efficient and not to mention transparent

@hodger did you happen to make any progress on this? care to share some of your downloaders?

@roclark would love to see this built-in!

**Comment by roclark** [comment]
Hey @vesper8, thanks for the additional feedback! I think now is a good time to revisit this, and you make a great point on lowering the server load on their side. I will try and work on a way to incorporate this with one of the upcoming releases. I think in the utility module, I can create a way to route the pulling of the webpage, and get it from a local directory. I will work on this a bit and see if I can get something going!
